name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master
  workflow_dispatch:      # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Create deployment package
        run: |
          zip -r deployment.zip . -x "*.git*" "*.github*" "*.gitignore"

      - name: Deploy to AWS Lambda
        run: |
          # Update Lambda function code
          aws lambda update-function-code \
            --function-name suchedule-service \
            --zip-file fileb://deployment.zip \
            --publish

          # Get the latest version number
          VERSION=$(aws lambda list-versions-by-function \
            --function-name suchedule-service \
            --query 'Versions[-1].Version' \
            --output text)

          # Update the production alias to point to the new version
          aws lambda update-alias \
            --function-name suchedule-service \
            --name production \
            --function-version $VERSION